# Generated by Django 3.1.1 on 2020-10-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
