# Generated by Django 3.1.1 on 2020-10-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customer_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='file',
            field=models.FileField(default='', upload_to='D:\\ak\\Project\\e-commerce-monitoring-system\\games_of_data\\games_of_data\\static\\media'),
        ),
    ]
