# Generated by Django 3.1.1 on 2020-10-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201011_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
