# Generated by Django 3.1.1 on 2020-10-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20201011_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='file',
        ),
    ]
