# Generated by Django 3.1.1 on 2020-11-08 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='dashboard.customer'),
        ),
    ]
