# Generated by Django 3.1.1 on 2020-11-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20201108_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='directory',
            new_name='azur_container',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='drive',
            new_name='azur_file_share',
        ),
    ]
