# Generated by Django 3.1.1 on 2020-11-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20201108_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='forgot_pwd_timestamp',
            field=models.FloatField(default=0),
        ),
    ]
