# Generated by Django 3.1.1 on 2020-11-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_customer_forgot_pwd_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('signup_timestamp', models.FloatField(default=0)),
            ],
        ),
    ]
