# Generated by Django 3.1.1 on 2020-11-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_signupverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_photo_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
